version: '2.3'

x-volumes:
  &default-volumes
    volumes:
      - ./modules:/app/profiles/govcms/modules/migration:${VOLUME_FLAGS:-delegated} ### Removed automatically in CI.
      - /app/sites/default/files

x-environment:
  &default-environment
    LAGOON_ROUTE: ${LOCALDEV_URL:-http://govcms-lagoon.docker.amazee.io}
    X_FRAME_OPTIONS: ${X_FRAME_OPTIONS:-SameOrigin}

services:

  cli:
    build:
      context: .
      dockerfile: $PWD/.docker/Dockerfile.govcms7
    image: ${DOCKERHUB_NAMESPACE:-govcmslagoon}/govcms7
    << : *default-volumes
    environment:
      << : *default-environment

  acsf:
    build:
      context: .
      dockerfile: $PWD/.docker/Dockerfile.acsf
      args:
        CLI_IMAGE: ${DOCKERHUB_NAMESPACE:-govcmslagoon}/govcms7
    image: ${DOCKERHUB_NAMESPACE:-govcmslagoon}/acsf
    << : *default-volumes
    depends_on:
      - cli
    environment:
      << : *default-environment

  test:
    build:
      context: .
      dockerfile: $PWD/.docker/Dockerfile.test
      args:
        CLI_IMAGE: ${DOCKERHUB_NAMESPACE:-govcmslagoon}/govcms7
    image: ${DOCKERHUB_NAMESPACE:-govcmslagoon}/test
    << : *default-volumes
    depends_on:
      - cli
    environment:
      << : *default-environment

  nginx:
    build:
      context: .
      dockerfile: $PWD/.docker/Dockerfile.nginx-drupal
      args:
        CLI_IMAGE: ${DOCKERHUB_NAMESPACE:-govcmslagoon}/govcms7
    image: ${DOCKERHUB_NAMESPACE:-govcmslagoon}/nginx-drupal
    << : *default-volumes
    environment:
      << : *default-environment
      LAGOON_LOCALDEV_URL: ${LOCALDEV_URL_NGINX:-http://govcms-lagoon-nginx.docker.amazee.io}
    networks:
      - amazeeio-network
      - default

  php:
    build:
      context: .
      dockerfile: $PWD/.docker/Dockerfile.php
      args:
        CLI_IMAGE: ${DOCKERHUB_NAMESPACE:-govcmslagoon}/govcms7
    image: ${DOCKERHUB_NAMESPACE:-govcmslagoon}/php
    environment:
      << : *default-environment

  mariadb:
    build:
      context: .
      dockerfile: $PWD/.docker/Dockerfile.mariadb-drupal
    image: ${DOCKERHUB_NAMESPACE:-govcmslagoon}/mariadb-drupal
    ports:
      - "3306" # Find port on host with `docker-compose port mariadb 3306`
    environment:
      << : *default-environment

  redis:
    build:
      context: .
      dockerfile: $PWD/.docker/Dockerfile.redis
    image: ${DOCKERHUB_NAMESPACE:-govcmslagoon}/redis
    environment:
      << : *default-environment

  solr:
    build:
      context: .
      dockerfile: $PWD/.docker/Dockerfile.solr
    image: ${DOCKERHUB_NAMESPACE:-govcmslagoon}/solr
    ports:
      - "8983" # Find port on host with `docker-compose port solr 8983`
    environment:
      << : *default-environment

  varnish:
    build:
      context: .
      dockerfile: $PWD/.docker/Dockerfile.varnish-drupal
    image: ${DOCKERHUB_NAMESPACE:-govcmslagoon}/varnish-drupal
    environment:
      << : *default-environment
      VARNISH_BYPASS: "true"
    networks:
      - amazeeio-network
      - default

networks:
  amazeeio-network:
    external: true
