#!/usr/bin/env bash
##
# GovCMS 7 Drupal deployment script.
#

# Run database updates if drupal is installed.
if ! drush status --fields=bootstrap | grep -q "Successful"; then
    drush updb -y
    drush cc all
else
    echo "Drupal not installed."
fi
