#!/usr/bin/env bash
##
# GovCMS 7 Drupal deployment script.
#

# Ensure tmp folder always exists.
mkdir -p /app/sites/default/files/private/tmp/

# Run database updates if drupal is installed.
if ! drush status --fields=bootstrap | grep -q "Successful"; then
    mkdir -p /app/sites/default/files/private/backups/ && drush sql-dump --ordered-dump --gzip --result-file=/app/sites/default/files/private/backups/pre-deploy-dump.sql
    drush updb -y
    drush cc all
else
    echo "Drupal not installed."
fi
