#!/usr/bin/env bash
##
# GovCMS 7 Drupal deployment script.
#

# Having this set to TRUE, which can be done as a runtime variable against a
# project environment, implies that we use this environment to test a site against
# changes like future versions of govcms images. In this scenario the database
# will be synced from PROD, ignoring any local database state.
# @todo this variable will get a new name, since it is part of a bigger piece of work around types of environments.
GOVCMS_TEST_CANARY=${GOVCMS_TEST_CANARY:-FALSE}

# Database options to configure the remote to use the read replica when
# performing read operations.
sync_opts=""
read_replica_enabled () {

  if [[ -z "$MARIADB_READREPLICA_HOST" ]]; then
    return
  fi

  if tables=$(drush @govcms-prod sqlq 'show tables;' --database=read 2> /dev/null) && [ -n "$tables" ]; then
    sync_opts="--source-database=read"
  fi
}

# Ensure tmp folder always exists.
mkdir -p /app/sites/default/files/private/tmp/

# Database updates, cache rebuild.
common_deploy () {
    drush updb -y
    drush cc all -y

    # Non production environments.
    if [[ ! -z "$LAGOON_ENVIRONMENT_TYPE" && "$LAGOON_ENVIRONMENT_TYPE" != "production" ]]; then
        # Enable stage file proxy post db-import.
        drush en stage_file_proxy -y
    fi
}

# Non production environments.
if [[ ! -z "$LAGOON_ENVIRONMENT_TYPE" && "$LAGOON_ENVIRONMENT_TYPE" != "production" ]]; then

    read_replica_enabled $sync_opts

    # Import production database on initial deployment (when database is empty).
    if tables=$(drush sqlq 'show tables;') && [ -z "$tables" ]; then
        # SQL sync only in Lagoon development environments.
        if [[ ! -z "$LAGOON_ENVIRONMENT_TYPE" && "$LAGOON_ENVIRONMENT_TYPE" != "local" ]]; then
            drush sql-drop -y
            drush sql-sync @govcms-prod @self $sync_opts -y
            common_deploy
        else
            echo "Drupal not installed."
        fi
    else
        # @see comments for GOVCMS_TEST_CANARY above.
        if [[ "$GOVCMS_TEST_CANARY" = TRUE ]]; then
            echo "GOVCMS_TEST_CANARY is set, syncing the database."
            drush sql-drop -y
            drush sql-sync @govcms-prod @self $sync_opts -y
        fi
        common_deploy
    fi
# Production environments.
else
    if tables=$(drush sqlq 'show tables;') && [ -n "$tables" ]; then
        mkdir -p /app/sites/default/files/private/backups/ && drush sql-dump --gzip --result-file=/app/sites/default/files/private/backups/pre-deploy-dump.sql
        common_deploy
        drush en -y govcms_lagoon && drush dis -y govcms_lagoon; drush pmu -y govcms_lagoon;
    else
        echo "Drupal not installed."
    fi
fi
