<?php

/**
 * @file
 * govCMS Akamai Fast Purge
 */

use Akamai\Open\EdgeGrid\Client;
use GuzzleHttp\Middleware;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\Exception\ClientException;

define('GAFP_WATCHDOG_TYPE', "govcms_akamai_fast_purge");

/**
 * Implements hook_permission().
 */
function govcms_akamai_fast_purge_permission() {
  return array(
    'akamai edgerc config check access' => array(
      'title' => t('Configuration check access.'),
      'description' => t('Will allow the user access to the advanced form field to show config detection.'),
    ),
    'administer akamai configuration' => array(
      'title' => t('Administer Akamai fast purge configuration'),
      'description' => t('Access and set the configuration for Akamai fast purge to consume.'),
    ),
    'administer akamai network' => array(
      'title' => t('Administer Akamai network'),
      'description' => t('Access and set the configuration for Akamai network.'),
    ),
    'manual akamai cache purge' => array(
      'title' => t('Submit path for purging'),
      'description' => t('Allow access to submit a path to clear from Akamai\'s cache'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function govcms_akamai_fast_purge_menu() {
  $items = [];

  $items['admin/config/services/akamai-fast-purge'] = [
    'title' => 'Akamai Fast Purge',
    'description' => 'Configuration for govCMS Akamai Fast Purge module',
    'page callback' => 'drupal_get_form',
    'page arguments' => ['govcms_akamai_fast_purge_form'],
    'access arguments' => ['administer akamai configuration'],
    'type' => MENU_NORMAL_ITEM,
  ];

  return $items;
}

/**
 * Fetch a list of configured extensions.
 *
 * @return array
 *   A flat array of supported extensions.
 */
function _govcms_akamai_get_configured_extensions() {
  $extensions = array();
  $support = array(
    'pdf' => variable_get('govcms_akamai_extensions_pdf', FALSE),
    'word' => variable_get('govcms_akamai_extensions_word', FALSE),
    'excel' => variable_get('govcms_akamai_extensions_excel', FALSE),
    'zip' => variable_get('govcms_akamai_extensions_zip', FALSE),
    'images' => variable_get('govcms_akamai_extensions_images', FALSE),
  );
  if (NULL != $support['pdf'] && 0 != $support['pdf'] && FALSE != $support['pdf']) {
    $extensions[] = 'pdf';
  }
  if (NULL != $support['word'] && 0 != $support['word'] && FALSE != $support['word']) {
    $extensions[] = 'docx';
    $extensions[] = 'doc';
  }
  if (NULL != $support['excel'] && 0 != $support['excel'] && FALSE != $support['excel']) {
    $extensions[] = 'xlsx';
    $extensions[] = 'xls';
  }
  if (NULL != $support['zip'] && 0 != $support['zip'] && FALSE != $support['zip']) {
    $extensions[] = 'zip';
  }
  if (NULL != $support['images'] && 0 != $support['images'] && FALSE != $support['images']) {
    $extensions[] = 'jpg';
    $extensions[] = 'jpeg';
    $extensions[] = 'png';
    $extensions[] = 'gif';
    $extensions[] = 'tiff';
  }

  sort($extensions);
  return $extensions;
}

/**
 * Page callback: Akamai Fast Purge settings
 *
 * @see govcms_akamai_fast_purge_menu()
 */
function govcms_akamai_fast_purge_form($form, &$form_state) {

  $form['vtabs'] = array(
    '#type' => 'vertical_tabs',
  );

  $form['general'] = array(
    '#type' => 'fieldset',
    '#title' => t('General'),
    '#description' => t('General settings for Akamai Fast Purge integration with govCMS'),
    '#group' => 'vtabs',
  );

  $form['support'] = array(
    '#type' => 'fieldset',
    '#title' => t('Extensions'),
    '#description' => t('Which extensions should be supported on this site?'),
    '#group' => 'vtabs',
  );

  $form['onetime'] = array(
    '#type' => 'fieldset',
    '#title' => t('One-time purge'),
    '#group' => 'vtabs',
    '#access' => user_access('manual akamai cache purge'),
  );

  $form['advanced'] = array(
    '#type' => 'fieldset',
    '#title' => t('Advanced'),
    '#description' => t('Advanced settings which you have access to, generally have security controls in place.'),
    '#group' => 'vtabs',
    '#access' => user_access('administer akamai network') || user_access('akamai edgerc config check access'),
  );

  $form['general']['govcms_akamai_fast_purge_enabled'] = [
    '#type' => 'checkbox',
    '#title' => t('Enable file purge on creation, update and deletion'),
    '#default_value' => variable_get('govcms_akamai_fast_purge_enabled', TRUE),
  ];

  $form['support']['govcms_akamai_extensions_pdf'] = array(
    '#type' => 'checkbox',
    '#title' => t('Purge PDF cache on create/update.'),
    '#default_value' => variable_get('govcms_akamai_extensions_pdf', FALSE),
  );
  $form['support']['govcms_akamai_extensions_word'] = array(
    '#type' => 'checkbox',
    '#title' => t('Purge DOCX/DOC cache on create/update.'),
    '#default_value' => variable_get('govcms_akamai_extensions_word', FALSE),
  );
  $form['support']['govcms_akamai_extensions_excel'] = array(
    '#type' => 'checkbox',
    '#title' => t('Purge XLSX/XLS cache on create/update.'),
    '#default_value' => variable_get('govcms_akamai_extensions_excel', FALSE),
  );
  $form['support']['govcms_akamai_extensions_zip'] = array(
    '#type' => 'checkbox',
    '#title' => t('Purge ZIP cache on create/update.'),
    '#default_value' => variable_get('govcms_akamai_extensions_zip', FALSE),
  );
  $form['support']['govcms_akamai_extensions_images'] = array(
    '#type' => 'checkbox',
    '#title' => t('Purge cache for supported image extensions on create/update.'),
    '#default_value' => variable_get('govcms_akamai_extensions_images', FALSE),
  );
  $form['onetime']['govcms_akamai_purge_path'] = array(
    '#type' => 'textfield',
    '#title' => t('Manual purge'),
    '#placeholder' => t('sites/default/files/file.pdf'),
    '#default_value' => '',
    '#size' => 40,
    '#maxlength' => 256,
    '#description' => t('Path to the URL for one-time manual purging.<br /><em>Do not include the domain or preceding slash (/)</em>'),
    '#access' => user_access('manual akamai cache purge'),
  );

  global $base_url;
  $form['advanced']['govcms_akamai_origin_url'] = array(
    '#type' => 'textfield',
    '#title' => t('Origin URL'),
    '#default_value' => variable_get('govcms_akamai_origin_url', $base_url),
    '#size' => 40,
    '#maxlength' => 256,
    '#description' => t('URL to use in each purge, which is protected via permissions'),
    '#access' => user_access('akamai edgerc config check access'),
  );

  $form['advanced']['govcms_akamai_fast_purge_api_network'] = array(
    '#type' => 'select',
    '#title' => t('Network'),
    '#options' => array(
      0 => t('staging'),
      1 => t('production'),
    ),
    '#default_value' => variable_get('govcms_akamai_fast_purge_api_network', 0),
    '#description' => t('The Akamai network to use.'),
    '#access' => user_access('administer akamai network'),
  );

  $form['advanced']['govcms_akamai_fast_purge_loglevel'] = array(
    '#type' => 'select',
    '#title' => t('Logging level'),
    '#options' => array(
      0 => t('None'),
      1 => t('Regular'),
      2 => t('Verbose'),
    ),
    '#default_value' => (int) variable_get('govcms_akamai_fast_purge_loglevel', 0),
    '#description' => t('Watchdog event logging support.'),
    '#access' => user_access('administer akamai network'),
  );

  $form['advanced']['govcms_akamai_fast_purge_credentials_path'] = array(
    '#type' => 'textfield',
    '#title' => t('Configuration'),
    '#default_value' => (_govcms_akamai_fast_purge_detect_edgerc_env()) ? 'Configuration detected' : 'No configuration detected',
    '#size' => 40,
    '#maxlength' => 256,
    '#description' => t('The API credentials are stored in a variable inside the hosting provider, this will simply check if the expected values have been detected..'),
    '#required' => TRUE,
    '#disabled' => TRUE,
    '#access' => user_access('akamai edgerc config check access'),
  );

  $form['advanced']['govcms_akamai_fast_purge_credentials_file'] = array(
    '#type' => 'textfield',
    '#title' => t('Configuration'),
    '#default_value' => (_govcms_akamai_fast_purge_detect_edgerc_file(getenv('HOME') . '/.edgerc')) ? 'Configuration file detected' : 'No configuration file detected',
    '#size' => 40,
    '#maxlength' => 256,
    '#description' => t('The API credentials are stored in a variable inside the hosting provider, this will simply check if the expected values have been detected..'),
    '#required' => TRUE,
    '#disabled' => TRUE,
    '#access' => user_access('akamai edgerc config check access'),
  );

  $extensions = _govcms_akamai_get_configured_extensions();
  if (count($extensions) === 0 || $extensions === '') {
    $extensions = '<em>No extensions have been configured.</em>';
  }
  else {
    $extensions = implode(', ', $extensions);
  }

  $form['support']['govcms_akamai_supported_extensions'] = array(
    '#type' => 'item',
    '#title' => t('Configured extensions'),
    '#markup' => "The following file extensions have been configured:<br />{$extensions}",
  );

  $form = system_settings_form($form);
  $form['#submit'][] = 'govcms_akamai_fast_purge_form_submit';
  return $form;
}

/**
 * Custom form submit handler for the custom purge path.
 */
function govcms_akamai_fast_purge_form_submit($form, $form_state) {
  // Purge a custom path.
  if (isset($form_state['values']['govcms_akamai_purge_path'])) {
    $custom_path = $form_state['values']['govcms_akamai_purge_path'];
    if ($custom_path != "" && user_access('manual akamai cache purge')) {
      if (_govcms_akamai_fast_purge_detect_edgerc_env() || _govcms_akamai_fast_purge_detect_edgerc_file(getenv('HOME') . '/.edgerc')) {
        if ((int) variable_get('govcms_akamai_fast_purge_loglevel', 0) >= 2) {
          watchdog(GAFP_WATCHDOG_TYPE, 'Manual purge requested of "@path"', ['@path' => $custom_path]);
        }
        _govcms_akamai_fast_purge_trigger($custom_path);
      }
      else {
        drupal_set_message('Akamai Fast Purge is enabled but no credentials have been provided.', 'warning');
      }
    }
  }
}

/**
 * Implements hook_file_insert().
 */
function govcms_akamai_fast_purge_file_insert($file) {
  _govcms_akamai_fast_purge_trigger($file);
}

/**
 * Implements hook_file_update().
 */
function govcms_akamai_fast_purge_file_update($file) {
  // We only need to purge the url if the file is being replaced.
  if (empty($file->replace_upload)) {
    return;
  }
  _govcms_akamai_fast_purge_trigger($file);
}

/**
 * Implements hook_file_delete().
 */
function govcms_akamai_fast_purge_file_delete($file) {
  _govcms_akamai_fast_purge_trigger($file);
}

/**
 * Detect if a configuration has been set.
 *
 * @param string $config
 *   The expected environment variable contents, for testing purposes.
 *
 * @return bool
 *   The result of the test to indicate a valid configuration.
 */
function _govcms_akamai_fast_purge_detect_edgerc_env($config = NULL) {
  return (count(_govcms_akamai_fast_purge_process_edgerc($config)) === 1) ? TRUE : FALSE;
}

/**
 * Detect if a configuration file is found.
 *
 * @param string $path
 *   The file path to the .edgerc file which we are not deviating from default.
 *
 * @return bool
 *   The result of the test to indicate a file was found at the specified path.
 */
function _govcms_akamai_fast_purge_detect_edgerc_file($path) {
  if ((NULL != $path) && ($path != "") && (file_exists($path))) {
    return TRUE;
  }
  return FALSE;
}

/**
 * Process data available in the edgerc file/variable.
 *
 * @param string $config
 *   The expected environment variable contents, for testing purposes.
 *
 * @return array|NULL
 *   The data object to be used as the Akamai configuration.
 */
function _govcms_akamai_fast_purge_process_edgerc($config = NULL) {
  if (NULL != $config) {
    $creds = $config;
  }
  else {
    $creds = getenv('EDGERC_PATH');
  }
  $data = explode(" ", $creds);
  $credentials = array();
  foreach ($data as $key => $data_item) {
    switch ($data_item):
      case 'host':
      case 'access_token':
      case 'client_token':
      case 'client_secret':
      case 'location':
        $credentials['default'][$data_item] = $data[$key + 2];
        break;
      default:
        break;
    endswitch;
  }
  return $credentials;
}

/**
 * Trigger the Akamai Fast Purge if needed.
 *
 * @param mixed $file
 *  The file object to be purged, or a string representing the (relative) URL/URI to the path/file
 *
 * @return  bool
 *   The responding value to the success of the API call.
 */
function _govcms_akamai_fast_purge_trigger($file) {
  $purge_enabled = variable_get('govcms_akamai_fast_purge_enabled', TRUE);
  if (!$purge_enabled) {
    return FALSE;
  }

  global $base_url;
  if (isset($file->uri)) {
    $path = drupal_realpath($file->uri);
    $parts = pathinfo($path);
    $extension = $parts['extension'];
    $purge_extensions = _govcms_akamai_get_configured_extensions();
    if (!in_array($extension, $purge_extensions)) {
      return FALSE;
    }
    $origin_url = variable_get('govcms_akamai_origin_url', $base_url);
    $file = "{$origin_url}${$path}";
  }
  else {
    $origin_url = variable_get('govcms_akamai_origin_url', $base_url);
    $file = "{$origin_url}/${file}";

  if ((int) variable_get('govcms_akamai_fast_purge_loglevel', 0) >= 1) {
    watchdog(GAFP_WATCHDOG_TYPE, 'Purging Url: @file', ['@file' => $target]);
  }

  if (_govcms_akamai_fast_purge_detect_edgerc_env() && count(_govcms_akamai_fast_purge_process_edgerc()) == 0) {
    drupal_set_message('Akamai Fast Purge is enabled but no credentials have been provided.', 'warning');
    return FALSE;
  }
  elseif (!_govcms_akamai_fast_purge_detect_edgerc_file(getenv('HOME') . '/.edgerc')) {
    return FALSE;
  }

  // Make the actual API call.
  _govcms_akamai_fast_purge_api_call($file);
  return TRUE;
}

/**
 * Make the API call to Akamai Purge.
 * @see https://github.com/akamai/AkamaiOPEN-edgegrid-php-client
 * @see https://developer.akamai.com/api/purge/ccu/resources.html
 *
 * @param $file
 * @param $credentials_path
 *
 * @param bool
 *   The true/false value of the success of the API call.
 */
function _govcms_akamai_fast_purge_api_call($file) {
  $credentials = _govcms_akamai_fast_purge_process_edgerc();
  require __DIR__.'/vendor/autoload.php';
  if (_govcms_akamai_fast_purge_detect_edgerc_env()) {
    $client = new Akamai\Open\EdgeGrid\Client();
    $client->setAuth($credentials['default']['client_token'], $credentials['default']['client_secret'], $credentials['default']['access_token']);
  }
  elseif (_govcms_akamai_fast_purge_detect_edgerc_file(getenv('HOME') . '/.edgerc')) {
    $client = Akamai\Open\EdgeGrid\Client::createFromEdgeRcFile('default', getenv('HOME') . '/.edgerc');
  }
  else {
    return FALSE;
  }

  $network_selection = variable_get('govcms_akamai_fast_purge_api_network', 0);
  $api_network = ((int) $network_selection == 1) ? 'staging' : 'production';
  $api_request_url = '/ccu/v3/invalidate/url/' . $api_network;

  $api_request_options = [
    'json' => [
      'objects' => [
        $file
      ],
    ],
    'handler' => _govcms_akamai_fast_purge_get_request_handler($client),
    'debug' => TRUE
  ];

  try {
    /** @var \GuzzleHttp\Psr7\Response $response */
    $response = $client->request('POST', $api_request_url, $api_request_options);
    $responseContent = $response->getBody()->getContents();
    if ((int) variable_get('govcms_akamai_fast_purge_loglevel', 0) >= 2) {
      watchdog(GAFP_WATCHDOG_TYPE, 'Request Completed - Full response: @response', ['@response' => $responseContent]);
    }
    return TRUE;
  }
  catch (ClientException $e) {
    $responseContent = $e->getResponse()->getBody()->getContents();
    if ((int) variable_get('govcms_akamai_fast_purge_loglevel', 0) >= 2) {
      watchdog(GAFP_WATCHDOG_TYPE, 'Request Failed: @err_msg | Full response: @response', ['@err_msg' => $e->getMessage(), '@response' => $responseContent], WATCHDOG_ERROR);
    }
    return FALSE;
  }
}

/**
 * Creates a request handler
 *
 * @param \Akamai\Open\EdgeGrid\Client $client
 *
 * @return mixed
 */
function _govcms_akamai_fast_purge_get_request_handler(Client $client) {
  // Grab the client's handler instance.
  $clientHandler = $client->getConfig('handler');

  // Create a middleware that echoes parts of the request.
  $tapMiddleware = Middleware::tap(function (Request $request) {
    // Prepare the message to write to watchdog.
    $message = "Sending Request - Path [@path] | Headers [@headers]";
    $message_vars = ['@path' => $request->getUri()->getPath(), '@headers' => ''];

    // Print out the headers.
    foreach ($request->getHeaders() as $name => $values) {
      $message_vars['@headers'] .= $name . ': ' . implode(', ', $values) . "; ";
    }
    if ((int) variable_get('govcms_akamai_fast_purge_loglevel', 0) >= 1) {
      watchdog(GAFP_WATCHDOG_TYPE, $message, $message_vars);
    }
  });

  return $tapMiddleware($clientHandler);
}
