<?php

/**
 * @file
 * Module file for the govCMS tweaks module.
 */

/**
 * Implements hook_views_bulk_operations_form_alter().
 *
 * Alter the first step of the VBO form (the selection page) to remove certain
 * actions when on the user administration pages. This is to prevent users
 * from escalating their role to administrator (as VBO does not out of the box
 * restrict access to these actions).
 *
 * @see https://govdex.gov.au/jira/browse/GOVCMS-2079
 *
 * @param $form
 * @param $form_state
 * @param $vbo
 */
function govcms_tweaks_views_bulk_operations_form_alter(&$form, &$form_state, $vbo) {
    global $user;

    $isAdminPeoplePage = strpos($_GET['q'], 'admin/people') === 0;
    $isAdmin = $user->uid === '1';
    $isVboForm = $form_state['step'] === 'views_form_views_form';
    if ($isAdminPeoplePage && !$isAdmin && $isVboForm) {
        unset($form['select']['operation']['#options']['action::views_bulk_operations_user_roles_action']);
        unset($form['select']['operation']['#options']['action::views_bulk_operations_modify_action']);
    }
}
