ARG CLI_IMAGE
FROM ${CLI_IMAGE} as cli

FROM govcmsdev/govcms7

COPY --from=cli /app /app

RUN drush dl \
  registry_rebuild \
  && rm -rf /home/.drush

COPY modules-acsf/ /app/sites/all/modules/acsf/
