ARG CLI_IMAGE
FROM ${CLI_IMAGE} as cli

FROM govcmsdev/test

COPY --from=cli /app /app

RUN /app/sanitize.sh \
  && rm -rf /app/sanitize.sh

COPY .docker/images/test/drutiny /app/sites/all/drutiny/profiles/

ENV SITE_AUDIT_VERSION 7.x-3.x
RUN wget https://github.com/govcms/audit-site/archive/$SITE_AUDIT_VERSION.tar.gz \
    && tar -C /tmp -xzvf $SITE_AUDIT_VERSION.tar.gz \
    && rm $SITE_AUDIT_VERSION.tar.gz \
    && mkdir -p /app/sites/all/drutiny \
    && mv /tmp/audit-site-$SITE_AUDIT_VERSION/* /app/sites/all/drutiny \
    && rm -Rf /tmp/audit-site-$SITE_AUDIT_VERSION \
    && php -d memory_limit=-1 /usr/local/bin/composer --working-dir=/app/sites/all/drutiny/ install --ignore-platform-reqs \
    && mv /app/sites/all/drutiny/profiles/drutiny /usr/bin/drutiny \
    && chmod +x /usr/bin/drutiny
