ARG CLI_IMAGE
FROM ${CLI_IMAGE} as cli

FROM govcmsdev/nginx-drupal:3.4

# nginx config.
COPY .docker/images/nginx/helpers/ /etc/nginx/helpers/
COPY .docker/images/nginx/x_frame_options.conf /etc/nginx/conf.d/drupal/location_drupal_append_x_frame_options.conf
COPY .docker/images/nginx/no_robots_govcms_host.conf /etc/nginx/conf.d/drupal/location_drupal_prepend_no_robots_govcms_host.conf
COPY .docker/images/nginx/no-robots.sh /lagoon/entrypoints/20-no-robots.sh
RUN fix-permissions /etc/nginx

COPY --from=cli /app /app

RUN /app/sanitize.sh \
  && rm -rf /app/sanitize.sh
