ARG CLI_IMAGE
FROM ${CLI_IMAGE} as cli

FROM govcmsdev/nginx-drupal

# nginx config.
COPY .docker/images/nginx/helpers/ /etc/nginx/helpers/
COPY .docker/images/nginx/x_frame_options.conf /etc/nginx/conf.d/drupal/location_drupal_append_x_frame_options.conf;
RUN fix-permissions /etc/nginx

COPY --from=cli /app /app

RUN /app/sanitize.sh \
  && rm -rf /app/sanitize.sh
